# Generated by Django 4.1 on 2022-09-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Company_name', models.CharField(max_length=200)),
                ('Email_name', models.CharField(max_length=200)),
                ('Phone_number', models.CharField(max_length=10)),
                ('Subject_name', models.CharField(max_length=100)),
                ('Password', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
